name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material pymdown-extensions 
      - run: pip install mkdocs-macros-plugin mkdocs-timetoread-plugin mkdocs-material-extensions
      - run: pip install mkdocs-plotly-plugin 
      - run: pip install -e .
      - run: mkdocs gh-deploy --force --clean --verbose